version: "3.9"

services:
  api:
    build:
      context: ./
      dockerfile: api.Dockerfile
    ports:
      - "3456:3456"
    volumes:
      - ./api/:/build
    depends_on:
      - db
  client:
    build:
      context: ./
      dockerfile: client.Dockerfile
    ports:
      - "8001:3000"
    volumes:
      - ./client/:/app
  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3321:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ginapp
      MYSQL_USER: ginapp
      MYSQL_PASSWORD: 123123123
    volumes:
      - ginapp-mysql:/var/lib/mysql

volumes:
  ginapp-mysql:
    driver: local