version: "3.5"
services:
  web:
    container_name: dockerdev
    build:
      context: ./
      dockerfile: dev.Dockerfile
    ports:
      - "3456:3456"
    volumes:
      - ./src/:/build
    depends_on:
      - db
  db:
    container_name: dockerdev-db
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3321:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ginapp
      MYSQL_USER: ginapp
      MYSQL_PASSWORD: 123123123
    volumes:
      - ginapp-mysql:/var/lib/mysql

volumes:
  ginapp-mysql:
    driver: local