// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	controllers2 "ginapp/auth/controllers"
	services2 "ginapp/auth/services"
	"ginapp/core/repositories"
	"ginapp/core/services"
	"ginapp/user/controllers"
	"gorm.io/gorm"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func initUserController(db *gorm.DB) controllers.UserController {
	userRepository := repositories.ProvideUserRepository(db)
	userService := services.ProvideUserService(userRepository)
	userController := controllers.ProvideUserController(userService)
	return userController
}

func initAuthController(db *gorm.DB) controllers2.AuthController {
	userRepository := repositories.ProvideUserRepository(db)
	authService := services2.ProvideAuthService(userRepository)
	authController := controllers2.ProvideAuthController(authService)
	return authController
}
